### ISSUE TITLE
Add support for High-Performance Order Storage (HPOS)

### ISSUE THREAD

**Issue by LeoOosterloo** [pronamic/wp-woocommerce-stock-synchronization#24]
WooCommerce is working on their new database structure instead of using the default WordPress structure.
This should improve the speed of WooCommerce websites big time.

https://woocommerce.com/document/high-performance-order-storage/

On my local setup I noticed the following setting. With a warning below it to not enable it because WooCommerce Stock Synchronisation is not compatible with it.

>**Enable the high performance order storage feature.** 
This feature shouldn't be enabled, the WooCommerce Stock Synchronization plugin is active and isn't compatible with it.

**Comment by remcotolsma** [comment]
We @pronamic decided on February 28, 2023 not to further develop and maintain this plugin. The setup of the plugin is not scalable enough and is quickly limited for many users because only inventory is synchronized. With the High-Performance Order Storage (HPOS) developments within WooCommerce, we have decided to archive this plugin.
